### ISSUE TITLE
Analysis ktools log tar empty

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#664]
## Issue Description
Analysis log tar empty, update to prevent chunk interference has broken the ktools log file tar `/v1/analyses/{id}/run_log_file/`

**Comment by sambles** [comment]
> **carlfischerjba**:  I noticed that the gulcalc logs are missing from the worker that runs the run_outputs task. Looks like they might get clobbered by that task. Not important now but might be useful to fix for future troubleshooting.

**Comment by sambles** [comment]
> **carlfischerjba** Looks like you can embed the node name and other info via environment variables.

https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
```
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
